### PR TITLE
WIP: swra124 flashing and python implementation

### PR DESCRIPTION
**Pull request by Maescool**
Initial work on making flashing to device work based and ported from the chipcon code in goodfet codebase

However it does not work as expected yet
old-flash is the way it was implemented in goodfet, but adresses seem to jump suddenly to lower addresses
I think this bricked my Yardstick, but i'm not sure.. so use caution when using this one!
I tried to then flash, with the addresses in correct order, and it seems to verify correctly..
however in my case, my yardstick doesn't boot :(

### CODE REVIEW

**Comment by Maescool** [comment]
Got flashing working!

**Comment by gkelly** [comment]
I've found it a lot more useful to drive things from the python side.  It also feels like it gives more flexibility in its use because the swra124 verbs are just transport details and you can handle the target specifics in python.

Is the performance of moving the flash logic to the greatfet that high, or is it primarily dominated by the flash writes?

**Comment by Maescool** [comment]
Well, I've basically ported the flashing code from the goodfet codebase, it was implemented like that over there, just wanted to get flashing working in the first place, to rescue my Yardstick.

I see no performance reasons, since the flash page is called every max page size times, so it could be moved to the python side..

**Comment by ktemkin** [comment]
> I've found it a lot more useful to drive things from the python side. It also feels like it gives more flexibility in its use because the swra124 verbs are just transport details and you can handle the target specifics in python.

This was predominantly how I'd envisioned GreatFET features being developed when I came up with the comms APIs: low-level methods in C, orchestrated by the higher-level APIs on the host side. 

That said, there are some benefits to having higher-level algorithms implemented in C: especially if you suspect that there's a reason your code might be useful "offline". An (unrelated) example: a user might want to have their GreatFET connected to a battery, and still use some of its firmware functionality.

It's a matter of opinion which features fall under that category. :)

> Is the performance of moving the flash logic to the greatfet that high, or is it primarily dominated by the flash writes?

In terms of user experience, the differences between having firmware handle these things and using batched USB commands is likely insignificant. I don't think optimization is really something to be worried about, here. :)

---

All in all, for something like this, I'm in favor of whatever implementations people want to provide. I'd rather accept a completed implementation than hold off for a perfect one. :)

**Comment by ktemkin** [comment]
Per discussion with @Maescool, closing this until it's ready for review. :)

**Pull request closed without merging**
