### PR TITLE
gpio: add support for configuring all gpio pin modes

### PR DESCRIPTION
**Pull request by antoinevg**
This PR adds support for configuring all of GreatFET's gpio pin modes:

```python
from greatfet.interfaces.gpio import Directions, InputConfiguration, OutputConfiguration, PullResistor, GlitchFilter, SlewRate

# You can configure pins via gpio.configure_pin():

gf.gpio.configure_pin((0,0), InputConfiguration(PullResistor.PULLDOWN))
gf.gpio.configure_pin((0,0), InputConfiguration(
        pull_resistor=PullResistor.PULLDOWN,
        glitch_filter=GlitchFilter.DISABLE,
    )
)
gf.gpio.configure_pin((0,0), OutputConfiguration(), False)
gf.gpio.configure_pin((0,0), OutputConfiguration(SlewRate.SLOW), initial_value=False)


# Or, if you prefer, directly on the pin:

pin = gf.gpio.get_pin("J1_P4")
pin.set_configuration(InputConfiguration(PullResistor.PULLDOWN))
pin.set_configuration(InputConfiguration(PullResistor.PULLDOWN, GlitchFilter.DISABLE))

# Or, even in other ways you may be accustomed:

pin = gf.gpio.get_pin("J1_P4")
pin.set_direction(Directions.OUT, True, OutputConfiguration(
        slew_rate=SlewRate.FAST
    )
)
```

See [host/greatfet/examples/gpio_pin_modes.py](https://github.com/antoinevg/greatfet/blob/antoinevg/gpio-mode/host/greatfet/examples/gpio_pin_modes.py) for more examples.

Supporting Pull Requests:

* https://github.com/greatscottgadgets/libgreat/pull/34 
* https://github.com/greatscottgadgets/libgreat/pull/35

References:

* https://github.com/greatscottgadgets/greatfet/issues/141
* https://github.com/greatscottgadgets/greatfet/issues/135

### CODE REVIEW

**Comment by martinling** [comment]
This changes the signature of the existing `set_up_pin` verb, which means that users must upgrade both the firmware and host code together. If new firmware is used with old host code, or old firmware used with new host code, then any of the methods in `class GPIO` that call `set_up_pin` will fail. I think this is a recipe for unhappy users.

I think what we ought to do is leave the old verb alone, add a new verb, and have the host code do some form of version detection before deciding which one to use.

**Comment by antoinevg** [comment]
EDIT: Ah, just need to check something! We'll be back! 🙈

**Comment by antoinevg** [comment]
So `libgreat`'s introspection capabilities are… great!

I've reverted the `set_up_pin` verb and added a `set_pin_resistor_mode` verb instead, which gives us a very clean:

```python
def set_up_pin(self, line, direction, initial_value=False, resistor_mode=ResistorMode.NO_PULL):
    # Set the initial configuration for the pin.
    self.api.set_up_pin(line[0], line[1], direction, initial_value)

    # If this is an input and the firmware supports it, set the resistor mode.
    if direction == Directions.IN and self.api.supports_verb("set_pin_resistor_mode"):
        resistor_modes = self.api.set_pin_resistor_mode(line[0], line[1], resistor_mode)
```

It also opens up a nice approach for how we can handle future pin configuration extensions such as slew etc...

That was great feedback, thank you!

**Review by martinling — CHANGES_REQUESTED** [review]
The new version avoids the forward/back compatilbility problems, but my concern now is that the host is now issuing two separate requests to the device, one to `set_up_pin` and then a second one to `set_pin_resistor_mode`.

Due to OS and USB bus scheduling, those requests may be quite some milliseconds apart, and during that time the pin is in an intermediate state, perhaps being pulled to an undesired level with unexpected effects.

I think we should include and use a new version of the `set_up_pin` verb, so that we can ensure that all the pin properties are changed together - they still won't quite be simultaneous, but any intermediate states will be bounded to no longer than the few cycles it takes the MCU to write to the relevant registers, rather than a much longer and less predictable duration between host requests.

While adding that new verb, we may also want to think about whether we should include any other properties besides the resistor mode, to avoid needing to add a further version later! There is a `TODO` comment in `gpio_verb_set_up_gpio_pin` which notes we may also want to add slew rate / drive strength settings.

**Review by martinling — DISMISSED** [review]
The current version addresses both the compatibility and single-request requirements, and the configuration objects look like a good model for adding these settings to other classes.

However, I see a new problem: this PR makes `NO_PULL` the default resistor mode. This is a functional change from previous releases, in which the pullups were always enabled. So this change may cause unexpected changes to the behaviour of user code. We should make `PULLUP` the default instead.

Now, one could argue that it would have been better to have disabled pullups from the start, and that it's better to rectify the mistake now. But actually this would never have been a great option, because the reset state of the LPC43xx is to enable the pullups on all pins. So any hardware attached at reset time has to be able to cope with the initial presence of a pullup, regardless of what the firmware or host code does.

Given that fact, it makes sense for the GreatFET API to have pullups as the default, so that when changing the initial input configuration, it is clear what it's being changed *from*.

One other point: both slew rates and drive strengths are only applicable to certain pins. Should we check applicability, and return an error if these settings are applied to pins where they are not available?

**Comment by antoinevg** [comment]
> However, I see a new problem: this PR makes `NO_PULL` the default resistor mode. This is a functional change from previous releases, in which the pullups were always enabled. So this change may cause unexpected changes to the behaviour of user code. We should make `PULLUP` the default instead.

Well this is where things get a little weird:

Inspecting the contents of the `scu_pin_configuration::pull_resistors` register right after reset I've seen various values of `0b00:PULLUP`, `0b10:NO_PULL` and even `0b11:PULLDOWN`.

_However_ -- once the pin has been configured as a gpio (`gpio_configure_pinmux`) it's consistently `0b10:NO_PULL` -- irrespective of whether it later gets configured as an input or output.

Not that any of this necessarily translates to what the actual physical pins are doing -- though they do seem a little floaty to me under test when you introduce some noise [1] to the circuit which tends to reinforce my feeling that we have been dealing with `NO_PULL` all along as explicitly configuring `PULLUP` behaves more like you'd expect.

What do you think?

[1] aka perturb tiny breadboard 😅

> One other point: both slew rates and drive strengths are only applicable to certain pins. Should we check applicability, and return an error if these settings are applied to pins where they are not available?

Ah, I knew there was one more thing I wanted to do! Tx!


### EDIT: Aha, mystery solved!

https://github.com/greatscottgadgets/libgreat/blob/19c10938988a6aa29a98edc1b6f08432d9554d1f/firmware/platform/lpc43xx/drivers/gpio.c#L464C1-L471C2

Looks like Kate set them to NO_PULL as default in 2019:

https://github.com/greatscottgadgets/libgreat/commit/afdc6baa4f2bbde0c2ef6309ad6ea66e16dd9eae

### EDIT: Which also makes me think…

To be consistent with Kate's code organization I should probably put the scu configuration code into libgreat rather than greatfet by adding a:

```
int gpio_configure_pinmux_and_scu(gpio_pin_t pin, platform_scu_pin_configuration_t configuration) { ... }
```

And modifying:
```
void platform_scu_configure_pin_gpio(uint8_t group, uint8_t pin, uint8_t function, scu_resistor_configuration_t resistors)
```

To rather be:

```
void platform_scu_configure_pin_gpio(uint8_t group, uint8_t pin, uint8_t function, platform_scu_pin_configuration_t configuration)
```

**Comment by martinling** [comment]
Ah, right!

I had observed that the pullups were on by default at startup (due to this causing some LEDs to be lit on Tycho/Sasserides, amongst other things), but I missed that they were then being disabled when the GPIOs were configured by the host. Resistor control was still listed as a `TODO`, and I didn't spot the diversion of `gpio_configure_pinmux` to `gpio_configure_pinmux_and_resistors` in libgreat, so it seemed like that setting just wasn't being touched at all.

This does indeed explain some floatiness, which I had thought was caused by the pullups just being quite weak.

So I guess the correct path is to go ahead and keep `NO_PULL` as the default in the GPIO class. That still leaves us with the messy situation of the pullups being enabled between reset and GPIO configuration by the host, but I guess we're stuck with that.

**Comment by martinling** [comment]
And yes, that reorganisation seems reasonable.

**Review by martinling — APPROVED** [review]
All looks good to me now.

**Pull request merged**
