### PR TITLE
Documentation: include installation and firmware upgrade information

### PR DESCRIPTION
**Pull request by francisrstokes**
Adding a little information about the initial setup to save others some time in figuring out that a DFU is required before use.

### CODE REVIEW

**Comment by francisrstokes** [comment]
@straithe Tagging you here after the discord chat. I'll take a look at documenting some bits for the facedancer repo as well

**Comment by straithe** [comment]
Thank you for your PR. The installation and fw update text we'd like to have in the greatfet documentation on Read the Docs and in this repository is on https://greatscottgadgets.github.io/greatfet-tutorials/getting-started.html from the beginning up to and including ```gf fw --auto```. This would be instead of the text that you have added so far. I'd be happy to accept your PR after that change.

**Review by straithe — CHANGES_REQUESTED** [review]
Thank you for your PR. The installation and fw update text we'd like to have in the greatfet documentation on Read the Docs and in this repository is on https://greatscottgadgets.github.io/greatfet-tutorials/getting-started.html from the beginning up to and including gf fw --auto. This would be instead of the text that you have added so far. I'd be happy to accept your PR after that change.

**Comment by francisrstokes** [comment]
@straithe sure - I've adjusted the docs according to the text you shared. I took the liberty of including OSX as a relevant system, and marked the udev rules section as linux specific.

**Pull request closed without merging**
