### PR TITLE
UART

### LINKED ISSUE #109: UART command-line tool
Implement UART control and bi-directional UART messages accessible from a command-line tool.  The tool should support stdin and stdout so that it can be used in a pipeline like netcat.

### PR DESCRIPTION
**Pull request by GravesJake**
resolves #109

### CODE REVIEW

**Comment by yuvadm** [comment]
@GravesJake I'd like to help get this PR updated and merged, can you update on its status and any open tasks that I can help with?

**Comment by yuvadm** [comment]
@GravesJake @ktemkin not sure how far the work on UART is coming along, but I'd love to see a feature that enable a transparent read/write bridge, something like opening `screen` on a `/dev/ttyUSB0` (e.g. from an FTDI device).

Again, would love to work on this myself if there is an up to date branch I can fork off of.

**Comment by ktemkin** [comment]
Yep — having a CDC-ACM connection working is one of the things I’ve been working on (and is relatively simple; it’s mostly adding the right descriptors, like this: https://github.com/ktemkin/GreatFET/commit/b3e98e7ebe2d3c157d91d9f10603d64ffadf5bc5#diff-cdbaccba71861f59bf15f33970307718R229).

There’s a `uart_driver` branch on my fork that needs to be updated — I’ll push a more updated / working branch in the next few days. :)

**Comment by craigknott** [comment]
I'm looking forward to this one.

**Comment by ktemkin** [comment]
Now outmoded by #274. :)

**Pull request closed without merging**
