### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by straithe**
Initial docs transfer to new format.

### CODE REVIEW

**Review by Qyriad — APPROVED** [review]

**Comment by miek** [comment]
It might be worth squashing https://github.com/greatscottgadgets/greatfet/pull/376/commits/17bf6d0ee7f9a3a62cf1af1e34e367066f35a766 into the previous commit before merging, otherwise that build output will always take up space in the repo history.

**Comment by Qyriad** [comment]
Oh, yeah, that's a good point, actually.

**Review by mossmann — APPROVED** [review]
love it!

**Comment by mossmann** [comment]
Can you squash and merge this, @Qyriad ?

**Comment by ktemkin** [comment]
not if we do it first >:D

**Comment by straithe** [comment]
Ha! Excellent. Thank you!

**Pull request merged**
